version: '3.9'

services:
  tempestas:
    build:
      context: ../
      dockerfile: ./build/package/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../configs:/app/configs
    depends_on:
      - redis
  redis:
    image: redis

