version: '3.9'

services:
  tempestas:
    build:
      context: ../
      dockerfile: ./build/package/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ../configs:/app/configs
    depends_on:
      - redis
    networks:
      - weather_app
  redis:
    image: redis
    volumes:
      - redis_data:/data
    networks:
      - weather_app

volumes:
  redis_data:
    driver: local

networks:
  weather_app:
    driver: bridge
