apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempestas
  labels:
    app: tempestas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempestas
  template:
    metadata:
      labels:
        app: tempestas
    spec:
      containers:
        - name: tempestas
          image: tempestas:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          volumeMounts:
          - name: config-volume
            mountPath: /app/configs
      volumes:
        - name: config-volume
          configMap:
            name: tempestas-config
            items:
            - key: config.yaml
              path: config.yaml
